name: Maven Compile & UT

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-java-build.yml@common-java-build
    with:
      process_env: Prod
      java_version: 8
    secrets: inherit