# Release component
name: Release

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
  workflow_dispatch:

jobs:
  on-build-failure:
    runs-on: ubuntu-latest

    steps:
      - name: Discard Staging
        uses: nexus-actions/drop-nexus-staging-repo@main
        with:
          username: ${{ secrets.OSSRH_USERNAME }}
          password: ${{ secrets.OSSRH_TOKEN }}
          staging_repository_id: ${{ needs.create_staging_repository.outputs.repository_id }}

  on-build-success:
    runs-on: ubuntu-latest

    steps:
      - name: Release
        # replace '@main' with the latest commit sha, see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
        uses: nexus-actions/release-nexus-staging-repo@main 
        with:
          username: ${{ secrets.OSSRH_USERNAME }}
          password: ${{ secrets.OSSRH_TOKEN }}
          staging_repository_id: ${{ needs.create_staging_repository.outputs.repository-id }}
          [description]: Closed ${{ github.repository }}#${{ github.run_number }}
          [close_only]: 'true'
